import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const packageRoot = new URL("../", import.meta.url);

test("package manifest excludes generated Python bytecode", async (t) => {
  const fixture = await mkdtemp(join(tmpdir(), "sdd-package-"));
  t.after(() => rm(fixture, { recursive: true, force: true }));
  const scriptDirectory = join(
    fixture,
    "skills",
    "sdd-orphan-audit",
    "scripts",
  );
  await mkdir(join(scriptDirectory, "__pycache__"), { recursive: true });
  await writeFile(
    join(fixture, "package.json"),
    await readFile(new URL("package.json", packageRoot), "utf8"),
    "utf8",
  );
  await writeFile(
    join(scriptDirectory, "sdd_orphan_audit.py"),
    await readFile(
      new URL(
        "skills/sdd-orphan-audit/scripts/sdd_orphan_audit.py",
        packageRoot,
      ),
      "utf8",
    ),
    "utf8",
  );
  await writeFile(
    join(scriptDirectory, "__pycache__", "probe.pyc"),
    "generated bytecode",
    "utf8",
  );

  const { stdout } = await execFileAsync(
    "npm",
    ["pack", "--dry-run", "--json"],
    { cwd: fixture },
  );
  const [packed] = JSON.parse(stdout);
  const paths = packed.files.map((file) => file.path);

  assert.ok(paths.includes("skills/sdd-orphan-audit/scripts/sdd_orphan_audit.py"));
  assert.ok(paths.every((path) => !path.includes("__pycache__")));
  assert.ok(paths.every((path) => !path.endsWith(".pyc")));
});
